# nixpacks.toml

[phases.setup]
nixPkgs = ["python310", "gcc", "postgresql"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[start]
cmd = "cd src && uvicorn mental_health_coach.main:app --host 0.0.0.0 --port $PORT" 